import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Sonner from '@/components/providers';
import Navbar from '@/components/sections/navbar';
import { Providers } from './providers';
import { auth } from '@/auth';
export const metadata: Metadata = {
  title: 'chhavi.me',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body className="font-manrope font-medium">
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Navbar />
            {children}
            <Sonner />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
